sudo: required
language: python
python:
- '3.5'
env:
  matrix:
  - TEST_PATTERN=TestNode
  global:
  - secure: QS9nRs8FWromOuGk0zOBNt54nAQzpRSEnW1BN5n013q2lQ50H5cqs0zlwMuILmK+ZXmIwW1cw25TZ583LVcSdrRQV66hTWTsKBuZHLmyOwSMdzAkiWEu+ABq2ORYdrZ9oCFv40aJng5COemRyx8KC9pchJufUBejnt9L0QcximYMFwkGjR9XHWUtjpU7QSurPFtgtE3T8N1XMXPzN0TmkHwahnyC3rkS1aBhU8eh/euVI9wIIvAvNd+yQxQhpHkrsZuLKPLWWkPGgBjuTFSzYlAb4t0uAR5JavshgBfmF28N+iArYjYGRlDNhBg5JRFmRZUxFNgdHbOksrx3yFSMlDhwvF72KXHaioNYPRjXfFYwa2VU2MOpeCK25493ITOaJWv9aPggs4zIZh+w09SRej87uKEF8+kiE5+ZJ8qKGGPqra3fXIhXU08SIvmNkB2h56i5zF0z8Yf1v1dhphSuy+c5bX/XJ5N/ED4lNakPRh7dSa/YUNr08fu9Jm/5fFofNgQM9ybRHkFYcFzxWkgPwAtsTzSz8sITFpnZj06FCmdkZyX3fFzaD0mKRC01e8kVT/TW6UHvN2sbyMJNpRe0+rpZmtdEUjQKZSsSrIF1XbKtdWiJX69ye9gpQ+MAloW2bilbUDu25yDSFr28cOY13wURut4RsJveEVo6JozBkAQ=
before_install: make ARTIFACT_URL=$ARTIFACT_URL download-artifact
