# This makes Travis CI use the container-based infrastructure which starts
# tests faster.
sudo: false

language: "python"

python:
  - "3.5"

before_install:
  - "pip install --upgrade pip setuptools"

install:
  - "pip install --upgrade --editable .[dev]"

cache: "pip"

before_script:
    - "make lint"

script:
    - "
      ARTIFACT_URL=https://downloads.dcos.io/dcos/testing/master/dcos_generate_config.sh ;
      DCOS_DOCKER_REPOSITORY=https://github.com/adamtheturtle/dcos-docker.git ;
      DCOS_DOCKER_BRANCH=macos-DCOS-15645 ;

      curl -o /tmp/dcos_generate_config.sh $ARTIFACT_URL ;
      git clone -b $DCOS_DOCKER_BRANCH $DCOS_DOCKER_REPOSITORY /tmp/dcos-docker ;
    "
    - "pytest -vvv"
