sudo: "required"

services:
  - "docker"

language: "python"

python:
  - "3.5"

before_install:
  - "pip install --upgrade pip setuptools"
  - "sudo apt-get update"
  # Ideally we would use `addons.apt.packages` for enchant but this is not
  # supported by the linter.
  - "sudo apt-get install docker-engine enchant"

install:
  - "pip install --upgrade --editable .[dev]"
  - "npm install"

cache: "pip"

before_script:
    - "make clean"

# Unfortunately Travis has a time out for total test run (50 minutes) and total time without
# output (10 minutes).
#
# We avoid the former by running only a small part of our test suite.
#
# We get around the latter by using `travis_wait` which hides all output
# until the tests are finished.
#
# We do not run tests in parallel as this uses too much space for Travis CI.
# The main use of space is the copying of the config file to each directory.
script:
    # For an unknown reason, `make` is shown to exit 0 in Travis CI even on
    # some errors.
    # We therefore check for error messages and exit 1 if one occurs.
    # This is not sustainable or robust.
    # We run it first to see output.
    - "make lint"
    - "if make lint 2>&1 | grep Error ; then exit 1; fi"
    - "if make lint 2>&1 | grep 'not found' ; then exit 1; fi"
    # - "git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '*.md$' || {
    #         echo 'Only the documentation was updated.';
    #         echo 'No tests will be run'.;
    #         echo 'No artifacts will be downloaded.';
    #         exit ;
    #    }
    #    "
    # - 'make download-dependencies'
    # - 'travis_wait 30 pytest -vvv -s -k TestIntegrationTests'
