group: deprecated-2017Q4
sudo: required
services:
- docker
language: python
python:
- '3.5'
env:
  matrix:
  - TEST_PATTERN=tests/test_enterprise.py::TestEnterpriseIntegrationTests::test_run_pytest
  - TEST_PATTERN=tests/test_enterprise.py::TestWaitForDCOS::test_auth_with_cli
  - TEST_PATTERN=tests/test_enterprise.py::TestCopyFiles::test_copy_files_to_installer
  - TEST_PATTERN=tests/test_node.py::TestNode
  - TEST_PATTERN=tests/test_cluster.py::TestIntegrationTests::test_run_pytest
  - TEST_PATTERN=tests/test_cluster.py::TestExtendConfig::test_extend_config
  - TEST_PATTERN=tests/test_cluster.py::TestExtendConfig::test_default_config
  - TEST_PATTERN=tests/test_cluster.py::TestClusterSize
  - TEST_PATTERN=tests/test_cluster.py::TestInstallDcosFromPathLogging
  - TEST_PATTERN=tests/test_cluster.py::TestMultipleClusters::test_two_clusters
  - TEST_PATTERN=tests/test_cluster.py::TestClusterFromNodes
  - TEST_PATTERN=tests/backends/test_docker.py::TestDockerBackend
before_install:
- echo $LICENSE_KEY_CONTENTS > /tmp/license-key.txt
- travis_retry pip install --upgrade pip setuptools codecov
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install docker-ce enchant
- travis_retry npm -g install npm@latest
install:
- travis_retry pip install --upgrade --process-dependency-links --editable .[dev]
- travis_retry npm install
cache: pip
before_script:
- make clean
- make lint
- travis_retry make EE_ARTIFACT_URL=$EE_ARTIFACT_URL download-artifacts
script:
- pytest -vvv -s "$TEST_PATTERN" --cov=src --cov=tests
after_success:
- codecov
