sudo: "required"

services:
  - "docker"

language: "python"

python:
  - "3.5"

before_install:
  - "pip install --upgrade pip setuptools"

install:
  - "pip install --upgrade --editable .[dev]"

cache: "pip"

before_script:
    - "make --ignore-errors clean"
    - "make lint"
    - 'docker ps'
    - 'docker -v'

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make download-dependencies; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_wait 30 pytest -vvv -s -x ; fi'
